-- Creating new warehouse
SELECT current_role();
USE ROLE SYSADMIN;
CREATE WAREHOUSE PRACTICE_TEST1 WITH WAREHOUSE_SIZE = MEDIUM
    AUTO_SUSPEND = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

-- make changes in existing warehouse
USE ROLE SYSADMIN;
ALTER WAREHOUSE PRACTICE_TEST1
SET WAREHOUSE_SIZE = LARGE;

-- Use Warehouse
USE WAREHOUSE PRACTICE_TEST1;

-- Create Transient Database; This type of databases only live for 1 day
USE ROLE SYSADMIN;
USE WAREHOUSE PRACTICE_TEST1;
CREATE OR REPLACE TRANSIENT DATABASE DEMO_DB;

-- Create Schema
USE ROLE SYSADMIN;
CREATE OR REPLACE SCHEMA DEMO_DB.BANKING;

-- Create Table
CREATE OR REPLACE TABLE DEMO_DB.BANKING.EMPLOYEES(
    ID INT,
    NAME STRING,
    DEPARTMENT VARCHAR(50),
    SALARY FLOAT,
    ADDRESS VARCHAR(100),
    REGULAR_EMPLOYEE BOOLEAN
);
